"""Compatibility helpers for Ella's clinic_note_skill outputs."""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Any

from pypdf import PdfReader

from .skill import evaluate_prior_authorization


def extract_text_from_pdf(pdf_path: str) -> dict[str, Any]:
    """
    Extract plain text from a clinical note PDF generated by clinic_note_skill.

    Args:
        pdf_path: Path to a generated note such as outputs/patient_93810.pdf.

    Returns:
        Dict with extracted text or an error.
    """
    path = Path(pdf_path)
    if not path.exists():
        return {"success": False, "error": f"PDF not found: {pdf_path}", "text": None}
    try:
        reader = PdfReader(str(path))
        text = "\n".join(page.extract_text() or "" for page in reader.pages)
        return {"success": True, "pdf_path": str(path.resolve()), "text": text}
    except Exception as exc:
        return {"success": False, "error": str(exc), "text": None}


def evaluate_prior_authorization_pdf(pdf_path: str) -> dict[str, Any]:
    """
    Evaluate a generated clinical note PDF against simulated payer criteria.

    Use this tool after Ella's clinic_note_skill creates a PDF in the outputs
    folder. The tool extracts text from the PDF, matches the insurance plan,
    checks criteria, and returns denial risk.
    """
    extracted = extract_text_from_pdf(pdf_path)
    if not extracted["success"]:
        return extracted
    result = evaluate_prior_authorization(extracted["text"])
    result["source_pdf"] = extracted["pdf_path"]
    return result


def _build_note_text_from_row(row: dict[str, str]) -> str:
    """Create note-like text from a CSV row using Ella's note field names."""
    outcome = int(float(row.get("Outcome", "0") or 0))
    diabetes = (
        "POSITIVE — Diabetes diagnosed"
        if outcome == 1
        else "NEGATIVE — No diabetes diagnosed"
    )
    return f"""
PRIOR AUTHORIZATION CLINICAL NOTE Medication: Ozempic (Semaglutide)
1. PATIENT DEMOGRAPHICS Patient ID {row.get("PatientID", "")}
Age {row.get("Age", "")} years
2. INSURANCE INFORMATION Insurance Plan {row.get("Insurance", "")}
3. VITAL SIGNS & LABORATORY MEASUREMENTS
Plasma Glucose (2-hr OGTT) {row.get("Glucose", "")} mg/dL
Body Mass Index (BMI) {row.get("BMI", "")} kg/m²
4. DIAGNOSIS Diabetes Status: {diabetes}
5. CLINICAL JUSTIFICATION FOR PRIOR AUTHORIZATION
Synthetic note generated from dataset row for insurance matching and denial-risk review.
"""


def evaluate_patient_from_csv(patient_id: str, csv_path: str) -> dict[str, Any]:
    """
    Evaluate a patient directly from the diabetes CSV used by clinic_note_skill.

    Args:
        patient_id: PatientID value, e.g. "93810".
        csv_path: Path to diabetes_updated.csv.

    Returns:
        Prior authorization evaluation result for that patient.
    """
    path = Path(csv_path)
    if not path.exists():
        return {"success": False, "error": f"CSV not found: {csv_path}"}
    with path.open(newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            if str(row.get("PatientID", "")).strip() == str(patient_id).strip():
                result = evaluate_prior_authorization(_build_note_text_from_row(row))
                result["source_csv"] = str(path.resolve())
                result["patient_id"] = str(patient_id)
                return result
    return {"success": False, "error": f"Patient ID {patient_id} not found in {csv_path}"}
