"""
Skill: insurance_match_skill
============================
Reads synthetic Ozempic prior authorization notes, matches Insurance A/B/C/D,
checks simulated payer criteria, flags missing documentation, and estimates
denial risk.

Designed to run after clinic_note_skill generates outputs/patient_<PatientID>.pdf.
"""

from __future__ import annotations

import csv
import re
from pathlib import Path
from typing import Any

from pypdf import PdfReader

GLUCOSE_DIABETES_THRESHOLD = 126.0
BMI_OBESITY_THRESHOLD = 30.0

POLICIES: dict[str, dict[str, Any]] = {
    "A": {
        "name": "Insurance A - Diabetes-focused policy",
        "summary": "Requires Type 2 Diabetes evidence and uncontrolled glucose.",
        "strictness": "medium",
    },
    "B": {
        "name": "Insurance B - Strict step therapy policy",
        "summary": "Requires diabetes evidence plus stronger step therapy support.",
        "strictness": "high",
    },
    "C": {
        "name": "Insurance C - Risk-based policy",
        "summary": "Requires diabetes evidence plus an added clinical risk factor.",
        "strictness": "medium",
    },
    "D": {
        "name": "Insurance D - Documentation completeness policy",
        "summary": "Focuses on complete objective data and provider rationale.",
        "strictness": "low",
    },
}


def _first_number(pattern: str, text: str) -> float | None:
    match = re.search(pattern, text, flags=re.IGNORECASE | re.DOTALL)
    return float(match.group(1)) if match else None


def _first_text(pattern: str, text: str) -> str | None:
    match = re.search(pattern, text, flags=re.IGNORECASE | re.DOTALL)
    return match.group(1).strip() if match else None


def _has_any(text: str, phrases: list[str]) -> bool:
    lower = text.lower()
    return any(phrase.lower() in lower for phrase in phrases)


def extract_text_from_pdf(pdf_path: str) -> dict[str, Any]:
    """Extract text from a PDF generated by clinic_note_skill."""
    path = Path(pdf_path)
    if not path.exists():
        return {"success": False, "error": f"PDF not found: {pdf_path}", "text": None}
    try:
        reader = PdfReader(str(path))
        text = "\n".join(page.extract_text() or "" for page in reader.pages)
        return {"success": True, "pdf_path": str(path.resolve()), "text": text}
    except Exception as exc:
        return {"success": False, "error": str(exc), "text": None}


def extract_patient_case(note_text: str) -> dict[str, Any]:
    """Extract prior authorization fields from synthetic note text."""
    diabetes_negative = _has_any(note_text, ["Diabetes Status: NEGATIVE", "No diabetes diagnosed"])
    diabetes_positive = (
        _has_any(
            note_text,
            [
                "Diabetes Status: POSITIVE",
                "diabetes diagnosed",
                "Type 2 diabetes diagnosis",
                "Type 2 diabetes mellitus",
            ],
        )
        and not diabetes_negative
    )
    return {
        "success": True,
        "patient": {
            "patient_id": _first_text(r"Patient\s+ID\s+(\d+)", note_text),
            "insurance_plan": _first_text(r"Insurance\s+Plan\s+([A-D])", note_text),
            "age": _first_number(r"Age\s+(\d+(?:\.\d+)?)\s+years", note_text),
            "medication_requested": _first_text(r"Medication:\s+([^\n\r]+)", note_text),
            "glucose_mg_dl": _first_number(r"Glucose.*?(\d+(?:\.\d+)?)\s*mg/dL", note_text),
            "bmi": _first_number(r"Body\s+Mass\s+Index\s+\(BMI\).*?(\d+(?:\.\d+)?)", note_text),
            "a1c": None,
            "diabetes_positive": diabetes_positive,
            "rationale_present": _has_any(note_text, ["clinical justification", "medically necessary", "medical necessity"]),
            "prior_therapy_present": _has_any(note_text, ["metformin", "failed", "prior medication", "alternative", "contraindicated"]),
            "safety_review_present": _has_any(note_text, ["pancreatitis", "thyroid", "men2", "allergy", "contraindication"]),
        },
        "notes": [
            "A1C is not available in the current dataset/note format.",
            "Glucose is used as the primary objective lab variable.",
        ],
    }


def list_policies() -> dict[str, Any]:
    """List simulated Insurance A/B/C/D policies."""
    return {"success": True, "policies": POLICIES}


def get_policy(policy_id: str) -> dict[str, Any]:
    """Return one simulated policy by ID A, B, C, or D."""
    normalized = policy_id.strip().upper()
    if normalized not in POLICIES:
        return {"success": False, "error": f"Unknown policy: {policy_id}"}
    return {"success": True, "policy_id": normalized, "policy": POLICIES[normalized]}


def evaluate_prior_authorization(note_text: str) -> dict[str, Any]:
    """Evaluate note text against matched simulated insurance criteria."""
    patient = extract_patient_case(note_text)["patient"]
    policy_id = patient["insurance_plan"]
    if not policy_id:
        return {"success": False, "error": "Insurance plan is missing.", "extracted_patient": patient}
    policy = get_policy(policy_id)
    if not policy["success"]:
        return policy

    glucose = patient["glucose_mg_dl"]
    bmi = patient["bmi"]
    passed: list[str] = []
    failed: list[str] = []
    missing: list[str] = []

    if patient["diabetes_positive"]:
        passed.append("Type 2 Diabetes / diabetes-positive status documented.")
    else:
        failed.append("No diabetes-positive status documented.")

    if glucose is None:
        missing.append("Plasma glucose measurement.")
    elif glucose >= GLUCOSE_DIABETES_THRESHOLD:
        passed.append(f"Glucose {glucose:g} mg/dL meets diabetes threshold >= 126 mg/dL.")
    else:
        failed.append(f"Glucose {glucose:g} mg/dL is below diabetes threshold >= 126 mg/dL.")

    if bmi is None:
        missing.append("BMI measurement.")
    elif bmi >= BMI_OBESITY_THRESHOLD:
        passed.append(f"BMI {bmi:g} kg/m² documents obesity risk factor >= 30.")
    else:
        failed.append(f"BMI {bmi:g} kg/m² does not meet obesity threshold >= 30.")

    if patient["rationale_present"]:
        passed.append("Provider medical necessity rationale is present.")
    else:
        missing.append("Provider medical necessity rationale.")

    if policy_id in {"A", "B"} and not patient["prior_therapy_present"]:
        missing.append("Prior therapy / step therapy history.")
    if policy_id == "B" and (glucose is None or glucose < 140):
        failed.append("Insurance B stricter glucose threshold >= 140 mg/dL is not met or missing.")
    if policy_id == "C" and not patient["safety_review_present"]:
        missing.append("Safety review: pancreatitis, thyroid cancer/MEN2, allergy, contraindications.")
    if patient["a1c"] is None:
        missing.append("A1C value, if required by payer.")

    risk_score = len(failed) * 2 + len(missing)
    risk_level = "high" if risk_score >= 5 else "medium" if risk_score >= 2 else "low"

    return {
        "success": True,
        "policy_id": policy_id,
        "policy": policy["policy"],
        "extracted_patient": patient,
        "criteria_passed": passed,
        "criteria_failed": failed,
        "missing_information": missing,
        "denial_risk": {"level": risk_level, "score": risk_score},
        "disclaimer": "Prototype only. Simulated payer rules are not real coverage decisions and require human review.",
    }


def evaluate_prior_authorization_pdf(pdf_path: str) -> dict[str, Any]:
    """Evaluate a PDF generated by clinic_note_skill."""
    extracted = extract_text_from_pdf(pdf_path)
    if not extracted["success"]:
        return extracted
    result = evaluate_prior_authorization(extracted["text"])
    result["source_pdf"] = extracted["pdf_path"]
    return result


def evaluate_patient_from_csv(patient_id: str, csv_path: str = "diabetes_updated.csv") -> dict[str, Any]:
    """Evaluate a patient directly from the dataset by PatientID."""
    path = Path(csv_path)
    if not path.exists():
        return {"success": False, "error": f"CSV not found: {csv_path}"}
    with path.open(newline="", encoding="utf-8-sig") as handle:
        for row in csv.DictReader(handle):
            if str(row.get("PatientID", "")).strip() == str(patient_id).strip():
                diabetes = "POSITIVE — Diabetes diagnosed" if int(float(row.get("Outcome", "0") or 0)) == 1 else "NEGATIVE — No diabetes diagnosed"
                note_text = f"""
PRIOR AUTHORIZATION CLINICAL NOTE Medication: Ozempic (Semaglutide)
Patient ID {row.get("PatientID", "")}
Age {row.get("Age", "")} years
Insurance Plan {row.get("Insurance", "")}
Plasma Glucose (2-hr OGTT) {row.get("Glucose", "")} mg/dL
Body Mass Index (BMI) {row.get("BMI", "")} kg/m²
Diabetes Status: {diabetes}
CLINICAL JUSTIFICATION FOR PRIOR AUTHORIZATION
Synthetic note generated from dataset row for insurance matching and denial-risk review.
"""
                result = evaluate_prior_authorization(note_text)
                result["source_csv"] = str(path.resolve())
                result["patient_id"] = str(patient_id)
                return result
    return {"success": False, "error": f"Patient ID {patient_id} not found in {csv_path}"}
